# Use Node.js official image
FROM node:16
 
# Set working directory
WORKDIR /app
 
# Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install
 
# Copy the rest of the application files
COPY . .
 
# Expose port
EXPOSE 5001
 
# Start the service
CMD ["node", "index.js"]
 